title: Yongfei-Hu's Homepage
page-top-title: Yongfei Hu
top-section-bg-text: Prevention is better than cure.
home-subtitle: Xidian University | Applied Statistics Graduate Student
#//home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Yongfei Hu 2025-2028. All Rights Reserved.'
